### ISSUE TITLE
SomeOne is selling this on codecanyon

### ISSUE THREAD

**Issue by mangaMag** [rattfieldnz/bitcoin-faucet-rotator#6]
https://codecanyon.net/item/btc-faucet-rotator-earn-passive-cryptocurrency/20550719

>>> SomeOne is selling this on codecanyon

you need to report him

**Comment by rattfieldnz** [comment]
Hi Jalakiva,

Thank you for messaging me about this. It irritates me that someone is willing to sell an open-sourced project for their own profit. The whole reason why I made this open-source is that the most likely users cannot afford to pay for it, and it is a way to give back to the Bitcoin/open-source communities.

Upon visiting the CodeCanyon link, I see the item has been removed. If you see any more instances of this happening, please do let me know. While people are free to modify the script however they please, **I DO NOT approve of anyone selling the script**.

**Comment by pratomoastan** [comment]
because this is opensource they didn't have the rights to sell it -.-
